const DEFAULT_INPUT_FOLDER = 'src';
const DEFAULT_OUTPUT_FOLDER = 'dist';
const DEFAULT_PROJECT_NAME = 'your awesome project';
const DEFAULT_PORT = 8000;
const DEFAULT_DIR = 'dream-ve-app';
const DEFAULT_PUBLIC_PATH = '';

module.exports = {
  DEFAULT_INPUT_FOLDER,
  DEFAULT_OUTPUT_FOLDER,
  DEFAULT_PROJECT_NAME,
  DEFAULT_PORT,
  DEFAULT_DIR,
  DEFAULT_PUBLIC_PATH,
};
